### ISSUE TITLE
Suitable for my concept or not

### ISSUE THREAD

**Issue by rebelholic** [FlemmingBehrend/feb-stepper#4]
Could your plugin suitable for my concept below?

![wizard bar concept](https://a.disquscdn.com/uploads/mediaembed/images/4186/1734/original.jpg)

These wizard bar using for report page generated from server

**Comment by FlemmingBehrend** [comment]
You would not be able to do it like your example without altering the component. You could make it look like that by changing the stylesheet (sass file) and initialising the component like this,.

``` html
// shows a stepper without headline that have 5 steps and all of them are completed.
<feb-stepper steps="['', '', '', '', '']" control="{}" start-step="5"></feb-stepper>
```

But my guess is that it would be easier to build a component that meet your demand, and then take some of the styles from this component and change the colors and size.

**Comment by rebelholic** [comment]
I have been trying on my Ionic App project just showed blank screen after followed your instruction above. Please fix it.

**Comment by FlemmingBehrend** [comment]
Could you link a github repo where you produce the error, then i Will try and look at it.

**Comment by rebelholic** [comment]
Here you go:

[Ionic App](https://github.com/rebelholic/wizardbar)

Please check "templates/playlists.html" file to more info

**Comment by FlemmingBehrend** [comment]
Just tried out the app, you only need to include feb-stepper as an angular dependency.

angular.module('starter', ['ionic', 'starter.controllers', 'feb.stepper'])

Then it will render, it will give a javascript error through because of the way ionic tries and set the step texts. It works if not using ionic, see the [example](https://github.com/FlemmingBehrend/feb-stepper/blob/master/example.html) here.

I don't have time right now to change the component to make it work in ionic, but you are welcome to fork and update it and I will pull it in.
