### ISSUE TITLE
Add ng-click to step

### ISSUE THREAD

**Issue by davidecampello** [FlemmingBehrend/feb-stepper#5]
Hi, thanks for the interesting directive!
I would like to add a ng-click to every step and call a function into my view scope to do some operations before setting the new active step.
How can i do this?
Thanks, 
regards

**Comment by FlemmingBehrend** [comment]
Hello

This repo will not be updated by me anymore. I am not working with angular anymore and because of work presure I am not going to maintain it. 

I will update the README.md file to reflect that.

You are free to clone and fix it and I will also merge any pull requests that have tests and passes ci.

regards, Flemming

**Comment by davidecampello** [comment]
Thanks
